import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Hero from "./_hero";
import Grids from "./_grids";
import Quote from "./_quote";
import GrAravs from "./_grids";

// btw please talk in comments!
//

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Greenzone </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script async src="https://cdn.splitbee.io/sb.js"></script>
      </Head>

      <main className={styles.main}>
        <Hero />

        <br />

        <Grids />

        <br />

        <Quote />

        <br />
      </main>
      <div></div>
      <footer className={styles.footer}>
        <a
          href="https://www.producthunt.com/makers-festival/green-earth"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className="text-green-500">
            {""} Created by kids and teenagers, for{" "}
            <span className="text-white">Maker festival </span>
          </span>
        </a>
      </footer>
    </div>
  );
}
