import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hero from './_hero'
import Grids from './_grids'




export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Greenzone </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
  
        <Hero/>
        
        <br />

        <Grids />

        <br />

      
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.producthunt.com/makers-festival/green-earth"
          target="_blank"
          rel="noopener noreferrer"
        >
        
          <span className={styles.logo}>
     A Product for Product Hunt Maker Festival 2021
          </span>
        </a>
      </footer>
    </div>
  )
}
